import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'
import './globals.css'
import MusicPlayer from '@/components/MusicPlayer'

const raleway = Raleway({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "We're getting married",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={raleway.className}>
        {children}
        <div className='fixed top-16 right-12 z-50'>
          <MusicPlayer />
        </div>
      </body>
    </html>
  )
}
